"""users confirmation

Revision ID: 768b9b2f5a56
Revises: f4bd5c9c6a52
Create Date: 2016-11-06 22:12:51.583041

"""

# revision identifiers, used by Alembic.
revision = '768b9b2f5a56'
down_revision = 'f4bd5c9c6a52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
