"""author

Revision ID: 977035ee61da
Revises: 60e2d9486bdf
Create Date: 2016-11-09 17:37:18.398097

"""

# revision identifiers, used by Alembic.
revision = '977035ee61da'
down_revision = '60e2d9486bdf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###
