"""avatar_info

Revision ID: 9b08ce2c3e22
Revises: 977035ee61da
Create Date: 2016-11-10 00:54:41.152295

"""

# revision identifiers, used by Alembic.
revision = '9b08ce2c3e22'
down_revision = '977035ee61da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
